project:
  type: website

website:
  title: "ISSS624"
  navbar:
    background: primary
    search: true
    left: 
      - text: "Hand-on Exercises"
        menu: 
          - text: Hands-on Exercise 1
            href: Exercises\\Hands-on_Ex1\\Hands-on_Ex1.qmd
          - text: Hands-on Exercise 2
            href: Exercises\\Hands-on_Ex2\\Hands-on_Ex2.qmd
          - text: Hands-on Exercise 3
            href: Exercises\\Hands-on_Ex3\\Hands-on_Ex3.qmd
          - text: Hands-on Exercise 4
            href: Exercises\\Hands-on_Ex4\\Hands-on_Ex4.qmd
      - text: "In-class Exercises"
        menu: 
          - text: In-class Exercise 1
            href: Exercises\\In-class_Ex1\\In-class_Ex1.qmd
          - text: In-class Exercise 2
            href: Exercises\\In-class_Ex2\\In-class_Ex2.qmd
          - text: In-class Exercise 3
            href: Exercises\\In-class_Ex3\\In-class_Ex3.qmd
          - text: In-class Exercise 4
            href: Exercises\\In-class_Ex4\\In-class_Ex4.qmd
      - text: "Take-Home Exercises"
        menu: 
          - text: Take-home Exercise 1
            href: Exercises\\Take-home_Ex1\\Take-home_Ex1.qmd
          - text: Take-home Exercise 2
            href: Exercises\\Take-home_Ex2\\Take-home_Ex2.qmd
    right:
      - href: index.qmd
        text: Home
      - text: "About" 
        file: about.qmd
        
        
    # sidebar:
    #   - title: "About"
    #     style: "docked"
    #     background: light
    #     #collapse-level: 2
    #     contents:
    #       - hands-on.qmd
    #       - Exercises\\Hands-on_Ex1\\Hands-on_Ex1.qmd
format:
  html:
    theme: flatly #alternative: lux
    css: styles.css
    toc: true
    code-overflow: wrap
    code-fold: true
    code-block-border-left: true
    code-summary: "Show the code"

editor: visual

